### ISSUE TITLE
Show speech mic when voice recognition is on

### ISSUE THREAD

**Issue by timblack1** [timblack1/rcl#32]
Doug is working on this.

Try using the `hardware:keyboard-voice` icon from https://elements.polymer-project.org/elements/iron-icons?view=demo:demo/index.html in an `iron-icon` Polymer element (see https://elements.polymer-project.org/elements/iron-icon).

**Comment by timblack1** [comment]
The code I've got looks like this:

```javascript
    toggle_voice_recognition:function(){
      if (this.voice_recognition_state === 'ON'){
        this.$.voice_recognition.stop();
        this.voice_recognition_state = 'OFF';
        this.querySelector('iron-icon').setAttribute('icon', 'av:mic-off');
      }else{
        this.$.search_for_a_church.value = '';
        this.$.voice_recognition.start();
        this.voice_recognition_state = 'ON';
        this.querySelector('iron-icon').setAttribute('icon', 'av:mic');
      }
    },
```

Use CSS like this to position the iron-icon:

```css
    iron-icon {
      display: inline-block;
      position: relative;
      float:right;
      top: -2em;
    }
```
